from django.urls import path
from . import views

urlpatterns = [
    path('seats/', views.members),
    path('all/', views.Concerts, name="concerts"),
    path('api/venues/', views.getAllVenues, name="concerts"),
    path('api/nextconcertid/', views.getNextConcertId, name="getnextconcertid"),
    path(r'<int:id>', views.ConcertPage, name="concertpage"),
    # path('test', views.displayMongoDbData, name='Concerts'),
    path('api/all', views.getAllConcerts, name='allconcerts'),
    path(r'api/bycountry/', views.getConcertByCountry, name='concertsbycountry'),
    path('api/mostpopular/', views.getConcertByMostPopular, name='concertsbymostpopular'),
    path(r'api/bygenre/', views.getConcertByGenre, name='concertsbygenre'),
    path(r'api/bycity/', views.getConcertByCity, name='concertsbycity'),
    path(r'api/bycityandcountry/', views.getConcertByCityAndCountry, name='concertsbycityandcountry'),
    path(r'api/byage/', views.getConcertByAgeToAttendAndBelow, name='concertsbyagetoattendandbelow'),
    path(r'api/bydateandtime/', views.getConcertByDateAndTime, name='concertsbydateandtime'),
    path(r'api/disability/', views.getConcertDisabilityAccessibility, name='concertsbydisabilityaccessibility'),
    path(r'api/byprice/', views.getConcertByCheapestSeatPrice, name='concertsbycheapestseatprice'),
    path('api/topsellers/', views.getConcertByTopSellers, name='concertsbycheapestseatprice'),
    path(r'api/deals/', views.getConcertByDeals, name='concertsbydeals'),
    path(r'api/venue/', views.getConcertByVenue, name='concertsbyvenuename'),
    path(r'api/performername/', views.getConcertByPerformerName, name='concertsbyperformername'),
    path('api/createconcert/', views.CreateANewConcert, name='createnewconcert'),
    path(r'api/concertbyid/', views.getConcertByID, name='concertbyid'),
    path(r'api/deleteconcert/', views.DeleteAConcert, name='deleteaconcert'),
    path('api/updateconcert/', views.UpdateANewConcert, name='updateconcert'),
    path('api/nextvenueid/', views.getNextVenueId, name='getnextvenueid'),
    path('api/createvenue/', views.CreateANewVenue, name='createnewvenue'),
    path('api/venuebyid/', views.getVenueByID, name='venuebyid'),
    path('api/updatevenue/', views.UpdateANewVenue, name='updatevenue'),
    path('api/deletevenue/', views.DeleteAVenue, name='deletevenue'),
]
